insert into EMPLOYEES (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES
(1, 'Beta', 'New', 'Beta@son.com'),
(2, 'omega', 'TOPS', 'Omega@yahoo.com'),
(3, 'Alpha', 'User', 'Alpha@gmail.com');

INSERT INTO ROLES (ID, NAME) VALUES
(1, 'ADMIN'),
(2, 'USER');

INSERT INTO USER (ID, USERNAME, PASSWORD, ACCOUNTEXPIRYDATE, ACCOUNTLOCKEDSTATUS, CREDENTIALSEXPIRYDATE, ACCOUNTENABLEDSTATUS) VALUES
(1, 'ADMIN', 'ADMIN', '2025-05-27', 1, '2025-05-27', 1),
(2, 'USER', 'USER',  '2025-05-27', 1, '2025-05-27', 1);